package com.smallchill.platform.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;
import java.util.Date;

/**
 * yesong
 * Generated by Blade.
 * 2016-09-14 11:35:10
 */
@Table(name = "tb_report")
@BindID(name = "ID")
@SuppressWarnings("serial")
public class Report extends BaseModel {

    @Column(name = "ID")
    private Integer id;
    @Column(name = "USERID")
    private Integer userId;
    @Column(name = "CONTENT")
    private String content;
    @Column(name = "TYPE")
    private String type;
    @Column(name = "STATUS")
    private Integer status;
    @Column(name = "CREATETIME")
    private Date createTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
